### ISSUE TITLE
Missing ui

### ISSUE THREAD

**Issue by mart368b** [Zentarg/Valheim-Worlds#2]
When i run 
```
py3 run Valheim-Worlds
```

it just tells me it that there is no such thing as "Valheim-Worlds" i mean what is that about?

**Comment by Zentarg** [comment]
I'm sorry to inform you, but we run on python 5.27, which solves all the issues regarding ui. Please upgrade your python version before running the program.

**Comment by mart368b** [comment]
ohhh thanks that worked
