### ISSUE TITLE
Better licensing

### ISSUE THREAD

**Issue by mart368b** [Zentarg/Valheim-Worlds#3]
I feel like this project should really be under mit license

**Comment by emildichmann272** [comment]
I can get behind this

**Comment by Zentarg** [comment]
This might take a while, I have assigned myself for when I have time to fix this issue, however we have other issues higher up on the priority list.

**Comment by mart368b** [comment]
that is understandable seing as this is the only issue
![billede](https://user-images.githubusercontent.com/22445645/109395083-c542aa80-792a-11eb-8fbf-b21db8de8723.png)

**Comment by mart368b** [comment]
Has there been any progress on this?

**Comment by Zentarg** [comment]
This has since been deemed a non-issue, and will not be fixed.
